version: '3.8'

services:
  flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=amqp://productionuser:productionpassword@haproxy:5672", "--port=5555"]
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://productionuser:productionpassword@haproxy:5672
      - FLOWER_BASIC_AUTH=admin:Ailyzeadmin
    depends_on:
      - haproxy
    networks:
      - ailyze-nw
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
          
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
